`ifndef FX_Q8_16_DEFS_VH
`define FX_Q8_16_DEFS_VH

// Generated by python/nominal_config.py from config/nominal.yaml.
// Active format: signed Q8.14; integer bits include the sign bit.
`define FX_Q8_16_WIDTH 22
`define FX_Q8_16_FRAC 14
`define FX_Q8_16_PRODUCT_WIDTH 44
`define FX_Q8_16_MAC_WIDTH 46
`define FX_Q8_16_RSQRT_ADDR_SHIFT 4
`define FX_Q8_16_ASIN_ADDR_SHIFT 3
`define FX_Q8_16_ONE 22'sd16384
`define FX_Q8_16_NEG_ONE -22'sd16384
`define FX_Q8_16_MAX 22'sh1fffff
`define FX_Q8_16_MIN 22'sh200000
`define FX_Q8_16_Q_DIAG 22'sd16
`define FX_Q8_16_R_DIAG 22'sd1638
`define FX_Q8_16_ALPHA 22'sd13073
`define FX_Q8_16_DIAG_FLOOR 22'sd16
`define FX_Q8_16_DET_FLOOR 22'sd16

`endif
