`ifndef FX_Q8_16_DEFS_VH
`define FX_Q8_16_DEFS_VH

// Generated by python/nominal_config.py from config/nominal.yaml.
// Active format: signed Q8.12; integer bits include the sign bit.
`define FX_Q8_16_WIDTH 20
`define FX_Q8_16_FRAC 12
`define FX_Q8_16_PRODUCT_WIDTH 40
`define FX_Q8_16_MAC_WIDTH 42
`define FX_Q8_16_RSQRT_ADDR_SHIFT 2
`define FX_Q8_16_ASIN_ADDR_SHIFT 1
`define FX_Q8_16_ONE 20'sd4096
`define FX_Q8_16_NEG_ONE -20'sd4096
`define FX_Q8_16_MAX 20'sh7ffff
`define FX_Q8_16_MIN 20'sh80000
`define FX_Q8_16_Q_DIAG 20'sd4
`define FX_Q8_16_R_DIAG 20'sd410
`define FX_Q8_16_ALPHA 20'sd3268
`define FX_Q8_16_DIAG_FLOOR 20'sd4
`define FX_Q8_16_DET_FLOOR 20'sd4

`endif
