#!/usr/bin/env python3
"""Validated YAML format contract and generated Verilog-2001 constants.

The q8_16 filenames/macros are compatibility names; nominal.yaml selects W/F.
The original real solver floors are 2**-10, independent of the selected F.
"""

from __future__ import annotations

import argparse
import json
import math
from pathlib import Path

import yaml

from common import ROOT, file_checksum, write_json


CONFIG_PATH = ROOT / "config" / "nominal.yaml"
HEADER_PATH = ROOT / "rtl" / "common" / "fx_q8_16_defs.vh"


def load_config(path: Path = CONFIG_PATH) -> dict:
    config = yaml.safe_load(path.read_text(encoding="utf-8"))
    expected_keys = {
        "system": {"state_dimension", "feature_dimension", "sigma", "rho", "beta", "sampling_interval", "taylor_order"},
        "experiment": {"seed", "steps", "rbkf_branches", "initial_state", "initial_covariance_diagonal"},
        "noise": {"process_covariance_diagonal", "measurement_covariance_diagonal"},
        "fixed_point": {"signed_width", "fractional_bits", "rounding", "saturation"},
    }
    if not isinstance(config, dict) or set(config) != set(expected_keys):
        raise ValueError("nominal.yaml must contain exactly system, experiment, noise, fixed_point")
    for section, keys in expected_keys.items():
        if not isinstance(config[section], dict) or set(config[section]) != keys:
            raise ValueError(f"Unexpected/missing nominal.yaml keys in {section}")
    fmt = config["fixed_point"]
    width, frac = fmt["signed_width"], fmt["fractional_bits"]
    if type(width) is not int or type(frac) is not int or (width, frac) not in ((24, 16), (22, 14), (20, 12)):
        raise ValueError("Supported signed Q8 formats are W/F=24/16, 22/14, 20/12 (sign included in 8)")
    if fmt["rounding"] != "nearest_ties_away_from_zero":
        raise ValueError("The baseline nearest_ties_away_from_zero policy must be preserved")
    if fmt["saturation"] != f"signed_{width}_bit":
        raise ValueError("saturation identifier must match signed_width")
    # This experiment changes only fixed_point. Fail if the nominal algorithm,
    # stochastic inputs, dimensions, or evaluation interval were also changed.
    original = {
        "system": {"state_dimension": 3, "feature_dimension": 3, "sigma": 10.0, "rho": 28.0,
                   "beta": 2.6666666666666665, "sampling_interval": 0.02, "taylor_order": 5},
        "experiment": {"seed": 20260820, "steps": 500, "rbkf_branches": 8,
                       "initial_state": [1.0, 1.0, 1.0], "initial_covariance_diagonal": 1.0},
        "noise": {"process_covariance_diagonal": 0.001, "measurement_covariance_diagonal": 0.1},
    }
    for section, values in original.items():
        if config[section] != values:
            raise ValueError(f"Bit-width-only experiment changed baseline {section} settings")
    return config


CONFIG = load_config()
WIDTH = CONFIG["fixed_point"]["signed_width"]
FRAC = CONFIG["fixed_point"]["fractional_bits"]
SCALE = 1 << FRAC
FX_MIN = -(1 << (WIDTH - 1))
FX_MAX = (1 << (WIDTH - 1)) - 1
Q_FORMAT = f"signed Q8.{FRAC}"
DIAG_FLOOR_REAL = 2.0 ** -10
DET_FLOOR_REAL = 2.0 ** -10


def quantize_constant(value: float) -> int:
    magnitude = int(math.floor(abs(value) * SCALE + 0.5))
    code = -magnitude if value < 0 else magnitude
    return min(max(code, FX_MIN), FX_MAX)


CONSTANTS = {
    "ONE": SCALE,
    "NEG_ONE": -SCALE,
    "MAX": FX_MAX,
    "MIN": FX_MIN,
    "Q_DIAG": quantize_constant(CONFIG["noise"]["process_covariance_diagonal"]),
    "R_DIAG": quantize_constant(CONFIG["noise"]["measurement_covariance_diagonal"]),
    "ALPHA": quantize_constant(math.sqrt(2.0 / math.pi)),
    "DIAG_FLOOR": quantize_constant(DIAG_FLOOR_REAL),
    "DET_FLOOR": quantize_constant(DET_FLOOR_REAL),
}


def render_header() -> str:
    digits = (WIDTH + 3) // 4
    lines = ["`ifndef FX_Q8_16_DEFS_VH", "`define FX_Q8_16_DEFS_VH", "",
             "// Generated by python/nominal_config.py from config/nominal.yaml.",
             f"// Active format: {Q_FORMAT}; integer bits include the sign bit."]
    for name, value in {"WIDTH": WIDTH, "FRAC": FRAC, "PRODUCT_WIDTH": 2 * WIDTH,
                        "MAC_WIDTH": 2 * WIDTH + 2, "RSQRT_ADDR_SHIFT": FRAC - 10,
                        "ASIN_ADDR_SHIFT": FRAC - 11}.items():
        lines.append(f"`define FX_Q8_16_{name} {value}")
    for name, value in CONSTANTS.items():
        # Bit patterns express MIN without negating the unrepresentable positive
        # magnitude in a WIDTH-bit signed decimal literal.
        if name in ("MIN", "MAX"):
            literal = f"{WIDTH}'sh{value & ((1 << WIDTH) - 1):0{digits}x}"
        else:
            literal = f"{'-' if value < 0 else ''}{WIDTH}'sd{abs(value)}"
        lines.append(f"`define FX_Q8_16_{name} {literal}")
    return "\n".join(lines + ["", "`endif", ""])


def validate_generated_header() -> None:
    if not HEADER_PATH.is_file() or HEADER_PATH.read_text(encoding="ascii") != render_header():
        raise ValueError("RTL header differs from nominal.yaml; run python/nominal_config.py --generate")


def validate_reference_format() -> None:
    summary_path = ROOT / "results" / "reference" / "summary.json"
    if not summary_path.is_file():
        raise ValueError("Missing reference summary; run python/nominal_models.py")
    summary = json.loads(summary_path.read_text(encoding="utf-8"))
    if (summary.get("signed_width"), summary.get("fractional_bits")) != (WIDTH, FRAC):
        raise ValueError("Reference arrays have a different/unknown W/F; regenerate with python/nominal_models.py")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--generate", action="store_true", help="Regenerate the derived RTL format header")
    args = parser.parse_args()
    if args.generate:
        HEADER_PATH.write_text(render_header(), encoding="ascii")
    validate_generated_header()
    write_json(ROOT / "results" / "bitwidth" / "format.json", {
        "q_format": Q_FORMAT, "signed_width": WIDTH, "fractional_bits": FRAC,
        "integer_bits_including_sign": WIDTH - FRAC, "scale": SCALE,
        "product_width": 2 * WIDTH, "three_term_mac_width": 2 * WIDTH + 2,
        "rounding": CONFIG["fixed_point"]["rounding"], "saturation": CONFIG["fixed_point"]["saturation"],
        "constants": CONSTANTS, "diagonal_floor_real": DIAG_FLOOR_REAL,
        "determinant_floor_real": DET_FLOOR_REAL, "config_sha256": file_checksum(CONFIG_PATH),
        "header_sha256": file_checksum(HEADER_PATH),
    })
    print(f"PASS: YAML/Python/RTL format contract {Q_FORMAT}, W={WIDTH}, F={FRAC}")


if __name__ == "__main__":
    main()
